import { Bot, RefreshCw, Sparkles } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts'
import Button from '../components/Button.jsx'
import Card from '../components/Card.jsx'
import EmptyState from '../components/EmptyState.jsx'
import MetricCard from '../components/MetricCard.jsx'
import PageHeader from '../components/PageHeader.jsx'
import { advisorApi } from '../services/api.js'
import { currency, percent } from '../utils/formatters.js'

const colors = ['#2dd4bf', '#60a5fa', '#f59e0b', '#fb7185', '#a78bfa', '#34d399']

export default function AiAdvisor() {
  const [plan, setPlan] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const applyPlan = async () => {
    try {
      const { data } = await advisorApi.plan()
      setPlan(data)
      setError('')
    } catch (err) {
      setError(err.response?.data?.detail || 'Unable to generate plan. Complete your profile and add transactions first.')
    }
  }

  const load = async () => {
    setLoading(true)
    setError('')
    try {
      await applyPlan()
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    let active = true
    advisorApi.plan()
      .then(({ data }) => {
        if (active) {
          setPlan(data)
          setError('')
        }
      })
      .catch((err) => {
        if (active) {
          setError(err.response?.data?.detail || 'Unable to generate plan. Complete your profile and add transactions first.')
        }
      })
    return () => {
      active = false
    }
  }, [])

  const allocation = useMemo(
    () => Object.entries(plan?.allocation_percent || {}).map(([name, value]) => ({ name, value })),
    [plan],
  )

  const amounts = useMemo(
    () => Object.entries(plan?.allocation_amount || {}).map(([name, value]) => ({ name, value })),
    [plan],
  )

  return (
    <>
      <PageHeader eyebrow="AI portfolio guidance" title="AI Advisor">
        <Button onClick={load} disabled={loading}><RefreshCw size={17} className={loading ? 'animate-spin' : ''} /> Refresh plan</Button>
      </PageHeader>

      {error ? <div className="mb-6 rounded-xl border border-amber-300/20 bg-amber-300/10 px-4 py-3 text-sm text-amber-100">{error}</div> : null}

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        <MetricCard icon={Bot} label="Investable surplus" value={currency(plan?.investable_amount || 0)} tone="teal" detail="Based on income minus expenses" />
        <MetricCard icon={Sparkles} label="Allocation classes" value={allocation.length || 0} tone="blue" detail="Generated by backend ML model" />
        <MetricCard icon={RefreshCw} label="Model state" value={loading ? 'Updating' : 'Ready'} tone="amber" detail="Uses live profile and money data" />
      </div>

      <div className="mt-6 grid gap-6 xl:grid-cols-[0.95fr_1.25fr]">
        <Card>
          <h2 className="text-xl font-semibold text-white">Suggested allocation</h2>
          <p className="text-sm text-slate-400">Portfolio split by percentage</p>
          <div className="mt-4 h-80">
            {allocation.length ? (
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie data={allocation} dataKey="value" nameKey="name" innerRadius={70} outerRadius={110} paddingAngle={4}>
                    {allocation.map((entry, index) => <Cell key={entry.name} fill={colors[index % colors.length]} />)}
                  </Pie>
                  <Tooltip contentStyle={{ background: '#0f172a', border: '1px solid rgba(255,255,255,.1)', borderRadius: 8 }} formatter={(v) => percent(v)} />
                </PieChart>
              </ResponsiveContainer>
            ) : (
              <EmptyState title="No plan yet" text="Refresh after adding profile and transaction data." />
            )}
          </div>
        </Card>

        <Card>
          <h2 className="text-xl font-semibold text-white">Allocation amounts</h2>
          <p className="text-sm text-slate-400">Recommended rupee deployment</p>
          <div className="mt-4 h-80">
            {amounts.length ? (
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={amounts}>
                  <CartesianGrid stroke="rgba(148,163,184,0.12)" vertical={false} />
                  <XAxis dataKey="name" stroke="#94a3b8" tickLine={false} axisLine={false} />
                  <YAxis stroke="#94a3b8" tickLine={false} axisLine={false} tickFormatter={(v) => `${Math.round(v / 1000)}k`} />
                  <Tooltip contentStyle={{ background: 'grey', border: '1px solid rgba(255,255,255,.1)', borderRadius: 8 }} formatter={(v) => currency(v)} />
                  <Bar dataKey="value" radius={[8, 8, 0, 0]}>
                    {amounts.map((entry, index) => <Cell key={entry.name} fill={colors[index % colors.length]} />)}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            ) : (
              <EmptyState title="No deployable capital" text="A positive surplus will produce concrete allocation amounts." />
            )}
          </div>
        </Card>
      </div>
    </>
  )
}
